# Generated by Django 5.2.11 on 2026-10-04 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_bulkorderrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bulkorderrequest',
            options={'ordering': ['-created_at'], 'permissions': [('manage_bulk_requests', 'Can manage bulk order requests')]},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'permissions': [('manage_catalog', 'Can manage the product catalogue')], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'permissions': [('manage_orders', 'Can manage customer orders')]},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'permissions': [('manage_catalog', 'Can manage the product catalogue'), ('manage_inventory', 'Can manage product inventory'), ('view_store_dashboard', 'Can view the store operations dashboard')]},
        ),
    ]
