# Generated by Django 5.2.11 on 2026-10-04 03:29

import django.db.models.deletion
from django.db import migrations, models


def backfill_order_snapshots(apps, schema_editor):
    Order = apps.get_model("store", "Order")
    database = schema_editor.connection.alias
    for order in Order.objects.using(database).select_related("product__category").iterator():
        product = order.product
        unit_price = (
            product.discount_price
            if product.discount_price is not None
            else product.price
        )
        Order.objects.using(database).filter(pk=order.pk).update(
            product_name_snapshot=product.name,
            product_brand_snapshot=product.brand,
            product_category_snapshot=product.category.name,
            unit_price_snapshot=unit_price,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_bulkorderrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_brand_snapshot',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='product_category_snapshot',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='product_name_snapshot',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='unit_price_snapshot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.RunPython(backfill_order_snapshots, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.product'),
        ),
    ]
