# Generated by Django 5.2.11 on 2026-10-04 03:34

from django.db import migrations, models


def set_initial_payment_status(apps, schema_editor):
    Order = apps.get_model("store", "Order")
    database = schema_editor.connection.alias
    Order.objects.using(database).filter(payment_method="UPI").update(
        payment_status="PENDING"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_product_brand_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PENDING', 'Payment pending verification'), ('PAID', 'Paid / verified'), ('FAILED', 'Failed'), ('PARTIALLY_REFUNDED', 'Partially refunded'), ('REFUNDED', 'Refunded')], default='UNPAID', max_length=24),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.RunPython(set_initial_payment_status, migrations.RunPython.noop),
    ]
