# Generated by Django 5.2.11 on 2026-10-04 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def record_opening_balances(apps, schema_editor):
    Product = apps.get_model("store", "Product")
    InventoryMovement = apps.get_model("store", "InventoryMovement")
    database = schema_editor.connection.alias
    opening_movements = [
        InventoryMovement(
            product_id=product.pk,
            reason="INITIAL",
            quantity_delta=product.stock,
            note="Opening balance when inventory history was introduced",
        )
        for product in Product.objects.using(database).filter(stock__gt=0).iterator()
    ]
    InventoryMovement.objects.using(database).bulk_create(opening_movements)


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_paid_at_order_payment_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('SALE', 'Sale'), ('CANCELLATION', 'Order cancellation'), ('RESTOCK', 'Restock'), ('ADJUSTMENT', 'Manual adjustment'), ('INITIAL', 'Opening stock')], max_length=20)),
                ('quantity_delta', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='store.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='store.product')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['product', '-created_at'], name='store_inven_product_e252ab_idx'), models.Index(fields=['reason', '-created_at'], name='store_inven_reason_0d87a6_idx')],
            },
        ),
        migrations.RunPython(record_opening_balances, migrations.RunPython.noop),
    ]
