# Generated by Django 5.2.11 on 2026-10-04 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_current_status(apps, schema_editor):
    Order = apps.get_model("store", "Order")
    OrderStatusEvent = apps.get_model("store", "OrderStatusEvent")
    database = schema_editor.connection.alias
    events = [
        OrderStatusEvent(
            order_id=order.pk,
            from_status="",
            to_status=order.status,
            note="Current status when order history was introduced",
        )
        for order in Order.objects.using(database).iterator()
    ]
    OrderStatusEvent.objects.using(database).bulk_create(events)


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_inventorymovement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PACKED', 'Packed'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], max_length=30)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_events', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_events', to='store.order')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.RunPython(seed_current_status, migrations.RunPython.noop),
    ]
