# Generated by Django 5.2.11 on 2026-10-04 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_deliveryzone_order_carrier_name_order_delivered_at_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='deliveryzone',
            constraint=models.CheckConstraint(condition=models.Q(('delivery_fee__gte', 0)), name='delivery_zone_fee_nonnegative'),
        ),
    ]
