# Generated by Django 5.2.11 on 2026-10-04 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_bulk_quote_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkquoteline',
            name='product_barcode_snapshot',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='bulkquoteline',
            name='product_sku_snapshot',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='product_barcode_snapshot',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='product_sku_snapshot',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
