# Generated by Django 5.2.11 on 2026-10-04 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerprofile',
            options={'ordering': ['-updated_at'], 'permissions': [('view_store_customers', 'Can view store customer accounts'), ('manage_store_customers', 'Can manage store customer accounts')], 'verbose_name': 'Customer Profile', 'verbose_name_plural': 'Customer Profiles'},
        ),
    ]
